# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9fc231efa092a91140699ab45da296e8a84d8839158d0cd7bb1b096688ffe48af09699fa47a8a8d5022e59bacd5ad2506503cfc0a7b1492e58bf191e516ac6c

test:
  secret_key_base: 94af088d390b9e4c036f076bcc01bbfb90e0b46b50af65d8048e3795fb0b45860dd36c3efc6bcf8cc25a3b4fc99fd08e40e076b8c7f495b7be794f81c42420b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
