# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bfb11f0807072e8294a1a815f3e2046bea70e8639ac2b893d6748fb631ac42f5e652c8b4359aecc8027e71281ca355be27ea5e36e7164c8106666ecf3f8c967

test:
  secret_key_base: dbcf83ea0e35eba8152eedf2803b730a5e2f64f1a0190969a74642d618c895e60e0e6bc2023d2d8b8a7a2dfb61a2dde2669d8bc8112097da59b99bb778cdc891

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
